# This is a basic workflow to help you get started with Actions

name: build with GCC toolchains

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout zerotier-magisk
        uses: actions/checkout@v4

      - name: Checkout ZeroTierOne
        uses: actions/checkout@v4
        with:
          repository: zerotier/ZeroTierOne
          path: ZeroTierOne

      - name: Checkout libnatpmp
        uses: actions/checkout@v4
        with:
          repository: miniupnp/libnatpmp
          path: libnatpmp

      # Runs a single command using the runners shell
      - name: Prepare GCC Toolchain
        run: |
          sudo apt-get install -qqy gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf g++-aarch64-linux-gnu g++-arm-linux-gnueabihf

      - name: Build for aarch64
        run: |
          CC=aarch64-linux-gnu-gcc
          CXX=aarch64-linux-gnu-g++

          cd libnatpmp
          make --silent CC=$CC natpmpc-shared
          cd ..

          cd ZeroTierOne
          make --silent -j $(nproc) ZT_STATIC=1 ZT_DEBUG=0 CC=$CC CXX=$CXX LDFLAGS="-L../libnatpmp -s" DEFS="-I../libnatpmp"
          cd ..

          mkdir -p magisk/zerotier/lib
          cp ZeroTierOne/zerotier-one magisk/zerotier
          cd magisk
          zip -q -r ../zerotier-magisk-aarch64-gcc.zip .

      - name: Build for arm
        run: |
          PATH=`pwd`/android-ndk-$ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          PATH=`pwd`/libnatpmp:$PATH
          NDK_ROOT=`pwd`/android-ndk-$ndk/toolchains/llvm/prebuilt/linux-x86_64

          CC=arm-linux-gnueabihf-gcc
          CXX=arm-linux-gnueabihf-g++

          cd libnatpmp
          make clean
          make CC=$CC natpmpc-shared
          cd ..

          cd ZeroTierOne
          make clean
          # sed -i "s/armv7ve/armv7a/g" make-linux.mk
          make -j $(nproc) ZT_STATIC=1 ZT_DEBUG=0 CC=$CC CXX=$CXX LDFLAGS="-L../libnatpmp -s" DEFS="-I../libnatpmp"
          cd ..

          cp ZeroTierOne/zerotier-one magisk/zerotier/
          cd magisk
          zip -q -r ../zerotier-magisk-arm-gcc.zip .

      # - name: Debugging with tmate
      #   uses: mxschmitt/action-tmate@v3.18

      - name: Get Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            zerotier-magisk-aarch64-gcc.zip
            zerotier-magisk-arm-gcc.zip
          tag_name: SNAPSHOT-GCC-${{ steps.date.outputs.date }}
          name: SNAPSHOT-GCC-${{ steps.date.outputs.date }}
          draft: false
          prerelease: true
